openapi: '3.0.1'
info:
  title: 'IdioSplash-API'
  version: '2023-10-16 16:38:59UTC'
paths:
  /GenerateOTP:
    post:
      summary: Generate OTP
      responses:
        200:
          description: Successful OTP generation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateOTPResponse'
        400:
          description: Invalid email for this organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        409:
          description: OTP previously generated for the email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error writing to the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Default response for POST /GenerateOTP
      x-amazon-apigateway-integration:
        payloadFormatVersion: '2.0'
        type: 'aws_proxy'
        httpMethod: 'POST'
        uri: 'arn:aws:apigateway:<REGION>:lambda:path/2015-03-31/functions/<GENERATE OTP LAMBDA ARN>/invocations'
        connectionType: 'INTERNET'
  /VerifyOTP:
    post:
      summary: Verify OTP
      responses:
        200:
          description: OTP verified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOTPResponse'
        500:
          description: Incorrect OTP or error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Default response for POST /VerifyOTP
      x-amazon-apigateway-integration:
        payloadFormatVersion: '2.0'
        type: 'aws_proxy'
        httpMethod: 'POST'
        uri: 'arn:aws:apigateway:<REGION>:lambda:path/2015-03-31/functions/<VERIFY OTP LAMBDA ARN>/invocations'
        connectionType: 'INTERNET'
x-amazon-apigateway-cors:
  allowMethods:
    - 'GET'
    - 'POST'
  allowHeaders:
    - 'content-type'
  maxAge: 0
  allowCredentials: false
  allowOrigins:
    - '<YOUR FRONTEND URL>'
x-amazon-apigateway-importexport-version: '1.0'
components:
  schemas:
    GenerateOTPResponse:
      type: object
      properties:
        email:
          type: string
    VerifyOTPResponse:
      type: object
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
